# Generated by Django 5.1.3 on 2024-11-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm_libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('ISBN', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
    ]
