# Generated by Django 5.1.3 on 2024-11-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm_libros', '0002_libros_delete_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='ISBN',
            field=models.IntegerField(unique=True),
        ),
    ]
