# Generated by Django 5.1.3 on 2024-11-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abm_libros', '0003_alter_libros_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='ISBN',
        ),
        migrations.AddField(
            model_name='libros',
            name='isbn',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
